name       : libgepub
version    : '0.5'
release    : 4
source     :
    - https://download.gnome.org/sources/libgepub/0.5/libgepub-0.5.tar.xz : 049486c9909445cafe6bf5bb8b3e4f746120614118b7e3512c1d5cd4c2d27e85
license    : LGPL-2.0
component  : programming.library
summary    : Library for handling epub documents
description: |
    libgepub is a GObject based library for handling and rendering epub documents.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
