name       : libgepub
version    : 0.7.0
release    : 15
source     :
    - https://download.gnome.org/sources/libgepub/0.7/libgepub-0.7.0.tar.xz : 210a4c7895c2e84f01a5682502ba5e8fa3ea896af3170fb2592fce1dda56e02e
license    : LGPL-2.0-only
component  : programming.library
summary    : Library for handling epub documents
description: |
    libgepub is a GObject based library for handling and rendering epub documents.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(webkit2gtk-4.1)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
