name       : libgepub
version    : 0.7.1
release    : 16
source     :
    - https://download.gnome.org/sources/libgepub/0.7/libgepub-0.7.1.tar.xz : a3e4b31a232659d26a54b9121b3882c3d7397c3cf44ae5c64b86700980bc7f60
license    : LGPL-2.0-only
component  : programming.library
summary    : Library for handling epub documents
description: |
    libgepub is a GObject based library for handling and rendering epub documents.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(webkit2gtk-4.1)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
