name       : libgepub
version    : 0.4
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgepub/0.4/libgepub-0.4.tar.xz : 5666a1c4d186d205bd2d91b71d4c1cd5426025569114a765dd913a564f149ff4
license    : LGPL-2.0
component  : programming
summary    : Library for handling epub documents
description: |
    libgepub is a GObject based library for handling and rendering epub documents.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
