name       : libgepub
version    : 0.6.0
release    : 10
source     :
    - https://download.gnome.org/sources/libgepub/0.6/libgepub-0.6.0.tar.xz : c78a395cc1d9c57b4485958ed83ffb96ed442750cfafa7797dd6d986b9f7b399
license    : LGPL-2.0-only
component  : programming.library
summary    : Library for handling epub documents
description: |
    libgepub is a GObject based library for handling and rendering epub documents.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
